version: '3'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: testDb
    ports:
      - 5432:5432
    volumes:
      - /data/postgres-data-sample:/var/lib/postgresql/data

  mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - "/data/mongo-data-ts6:/data/db"
